
services:
  mssql:
    container_name: sql-db
    image: mcr.microsoft.com/azure-sql-edge
    environment:
      ACCEPT_EULA: '1'
      SA_PASSWORD: 'Password@1'
    ports:
      - "1434:1433"
    volumes:
      - data-sql:/var/opt/mssql 
    
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  data-sql:
  redis-data: