@API_HostAddress = https://localhost:5000


GET {{API_HostAddress}}/api/buggy/notfound
###

GET {{API_HostAddress}}/api/buggy/servererror
###

GET {{API_HostAddress}}/api/buggy/unauthorized

###

GET {{API_HostAddress}}/api/buggy/badrequest

###
